# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-13 19:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='submitted',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='book',
            name='thumbnail',
            field=models.ImageField(default='static/default_book_image.png', upload_to='books/thumbnails'),
        ),
    ]
