# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-02 23:45
from __future__ import unicode_literals

import books.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='teacher',
        ),
        migrations.AlterField(
            model_name='book',
            name='thumbnail',
            field=models.ImageField(upload_to=books.utils.get_image_file_path),
        ),
    ]
