# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-13 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20170413_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='sold',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='thumbnail',
            field=models.ImageField(default='/static/default_book_image.png', upload_to='books/thumbnails'),
        ),
    ]
