# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-14 22:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_book_listed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(default='No description.'),
        ),
        migrations.AlterField(
            model_name='book',
            name='thumbnail',
            field=models.ImageField(default=b'/static/images/books/default_book_image.png', upload_to='books/thumbnails'),
        ),
    ]
