# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-16 02:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_auto_20170414_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='submitted',
            field=models.DateField(default=datetime.datetime(2017, 4, 16, 2, 56, 7, 804115)),
        ),
    ]
