# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-16 21:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_auto_20170416_0256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(default='.', max_length=13),
        ),
        migrations.AlterField(
            model_name='book',
            name='submitted',
            field=models.DateField(default=datetime.datetime.today),
        ),
    ]
