# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 01:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_auto_20170416_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(default='.', max_length=20),
        ),
    ]
