# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 19:24
from __future__ import unicode_literals

import books.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_auto_20170418_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='condition',
            field=models.CharField(choices=[(b'New', b'New'), (b'Like New', b'Like New'), (b'Very Good', b'Very Good'), (b'Good', b'Good'), (b'Acceptable', b'Acceptable')], max_length=20),
        ),
        migrations.AlterField(
            model_name='book',
            name='thumbnail',
            field=models.ImageField(default='books/thumbnails/default_book_image.png', upload_to=books.utils.get_image_file_path),
        ),
    ]
