# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 19:49
from __future__ import unicode_literals

import books.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_auto_20170425_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(default='.', max_length=20, validators=[books.utils.check_isbn_length, books.utils.check_isbn_validity]),
        ),
    ]
